apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 6
  selector: 
    matchLabels:
      app: httpd
    template:
      metadata:
        labels: 
          app: httpd
      spec:
        containers:
        - name: httpd
          image: httpd:2
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: httpd
            
          volumeMounts:
          - name: fileserver-httpd
            mountPath: /usr/local/apache2/htdocs/
        volumes: 
        - name: fileserver-httpd
          persistentVolumeClaim:
            claimName: fileserver-httpd