apiVersion: v1
kind: Pod
metadada:
  name: myapp-php
spec:
  - name: myapp-php
    image: denilsonbonatti/myapp-php:1.0
    ports:
    - containerPort: 80
    
 ---
 
apiVersion: v1
kind: Service
metadada:
  name: myapp-php-service
spec:
  type: NodePort
  selector:
    app: myapp-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005